### ISSUE TITLE
Only purchased cars can be driven

### ISSUE THREAD

**Issue by iGabyTM** [A5H73Y/Carz#14]
I've updated to 6.2 and looks like if `OnlyOwnedCarsDrive` is `true` and you try to drive a normal mincart or a car spawned with `/carz spawn` you can't, only purchased cars work, but if you turn `OnlyOwnedCarsDrive` to `false` everything works fine. (Maybe I do something wrong)

**Comment by A5H73Y** [comment]
Fixed as part of 6.0 rewrite.
