### ISSUE TITLE
Problem with ClimbBlocks

### ISSUE THREAD

**Issue by JavaCalorious** [A5H73Y/Carz#18]
I'm running a 1.8 Bukkit Server but it doesn't work. I added slab and quartz blocks into the CB list, yet it still doesn't work.
![image](https://user-images.githubusercontent.com/40225169/47255063-5ffa6700-d49d-11e8-8cf6-7a86e6dea671.png)

**Comment by A5H73Y** [comment]
This is intended functionality currently. The way climb blocks currently work is that it will check what block is **below** you, if it is a climb block, you will elevate.
