### ISSUE TITLE
will hurt player in car in paper 1.14.4

### ISSUE THREAD

**Issue by PointTorrent** [A5H73Y/Carz#28]
Player will be hurt after clicking in his car, using his key(stick). It's likely that the player is asphyxiated in a block. Maybe this plugin has something incompatible with paperspigot?
server：paper-243，minecraft 1.14.4
plugin: carz-7.0, vault, protocollib (both the latest version), no other plugins

**Comment by A5H73Y** [comment]
I've just tried the latest version of paper with the latest Carz snapshot and am unable to replicate this problem. Can you please try again and reopen the ticket if found?
