### ISSUE TITLE
RegEx when creating a new car is wrong when specifying the block.

### ISSUE THREAD

**Issue by ayunami2000** [A5H73Y/Carz#36]
When specifying the block for the car to have in it when creating a new car, the RegEx doesn't allow underscores so many blocks cannot be used. E.g., `campfire` works but `oak_stairs` does not work.

The fix would be to simply add an underscore into the RegEx on [line 24 of CreateCarTypeConversation.java](https://github.com/A5H73Y/Carz/blob/master/src/main/java/io/github/a5h73y/carz/conversation/CreateCarTypeConversation.java#L24)
```
Note: Enter 'cancel' to quit the conversation.
 What would you like this car to be called?
test
 What should the Car's Start Speed be?
 (default = 60.0)
60
 What should the Car's Max Upgrade Speed be?
 (default = 120.0)
120
 What should the Car's Acceleration be?
 (default = 1.0)
1
 What should the Fill Material be?
 (default = AIR)
OAK_STAIRS
Invalid Value.. Please try again...
 What should the Fill Material be?
 (default = AIR)
OAK_PLANK
Invalid Value.. Please try again...
 What should the Fill Material be?
 (default = AIR)
OAK_PLANKS
Invalid Value.. Please try again...
 What should the Fill Material be?
 (default = AIR)
SNOW
 All done, test created.
```

**Comment by A5H73Y** [comment]
Yes you are correct, not entirely sure why there is a filter on there now that I think about it... as the Material lookup will fail to find it if it's invalid.
Thank you for reporting this.

**Comment by A5H73Y** [comment]
Fixed in latest commit.
