### ISSUE TITLE
Does not work with EssentialsX

### ISSUE THREAD

**Issue by dannysmc95** [A5H73Y/Carz#39]
Hey,

Nice mod, but I have an issue with getting it to work with EssentialsX.
I use the built in EssentialsX permissions, and I have added it to the `player-commands` section.
I have tried:

```plaintext
Carz.Purchase
```

And

```plaintext
carz.purchase
```

Both still do not allow the user to run the purchase command, well tbh, the user can't run any commands.

Anyway around this?
Thanks in advance.

**Comment by Notplayingallday383** [comment]
I have the same issue do you know how to fix it?

**Comment by dannysmc95** [comment]
@Notplayingallday383 

Nope, I stopped using it 🤷🏻 looks like the project is pretty much dead.
